name: enzyme_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - _openmp_mutex=4.5
  - appnope=0.1.4
  - aria2=1.37.0
  - asttokens=3.0.1
  - backports.zstd=1.2.0
  - biopython=1.86
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - diamond=2.1.17
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - gawk=5.3.1
  - gmp=6.3.0
  - gsl=2.7
  - h2=4.3.0
  - hmmer=3.4
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libasprintf=0.25.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libintl=0.25.1
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - mafft=7.526
  - matplotlib-inline=0.2.1
  - mmseqs2=18.8cc5c
  - mpfr=4.2.1
  - mpi=1.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.2.6
  - openmpi=4.1.6
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pyzmq=27.1.0
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.2
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - tqdm==4.67.1
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/enzyme_env
